workflows:
  ios:
    name: iOS Build
    max_build_duration: 120
    environment:
      groups:
        - apple-authentication   # Reference the variable group here
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd ios_app
          flutter pub get
          cd ios
          pod install --repo-update
      - name: Build iOS App
        script: |
          cd ios_app
          flutter build ios --release --no-codesign  # --codesign if you use code signing
          ls -la build/ios/iphoneos  # Add this to check if the app is being generated
      - name: List contents of the build directory
        script: |
          echo "Listing contents of build/ios/iphoneos"
          ls -R build/ios/iphoneos
      - name: Deploy to TestFlight
        script: |
          xcrun altool --upload-app -f build/ios/iphoneos/Runner.app -t ios --username "$APPLE_ID" --password "$APPLE_PASSWORD"
    artifacts:
      - build/ios/iphoneos/Runner.app
