workflows:
  ios:
    name: iOS Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd ios_app
          flutter pub get
          cd ios
          pod install --repo-update
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign  # Change to --codesign if you are using code-signing
      - name: Deploy to TestFlight
        script: |
          xcrun altool --upload-app -f build/ios/iphoneos/Runner.app -t ios --username "$APPLE_ID" --password "$APPLE_PASSWORD"
    artifacts:
      - build/ios/iphoneos/Runner.app
