# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'TensorFlowLiteSwift', '~> 2.12.0'
  pod 'TensorFlowLiteC', '~> 2.12.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
