# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Ensure Flutter environment is loaded before using Flutter-specific pod installation
flutter_root = File.expand_path('..', File.dirname(__FILE__))
load File.join(flutter_root, 'ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  # Enable dynamic frameworks to properly link TensorFlow Lite
  use_frameworks! :linkage => :static

  # Pods for Runner
  pod 'TensorFlowLiteC', :modular_headers => false

  # Ensure Flutter dependencies are installed
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

  
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
      config.build_settings['STRIP_STYLE'] = 'non-global'
      config.build_settings['DEAD_CODE_STRIPPING'] = 'NO'
    end
  end
end


