name: Build iOS App for iOS without signing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'

      # Install dependencies (flutter packages)
      - name: Install Flutter dependencies
        run: |
          cd federated_slm_app
          flutter clean
          flutter pub get
      
      # Install iOS dependencies (CocoaPods)
      - name: Install iOS CocoaPods dependencies
        run: |
          cd federated_slm_app
          cd ios
          pod deintegrate
          pod install

      # Build iOS app without signing
      - name: Build iOS app without signing
        run: |
          cd federated_slm_app
          flutter build ios --no-codesign

      # Archive the iOS app (no signing)
      - name: Archive iOS app
        run: |
          cd federated_slm_app
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath $PWD/build/Runner.xcarchive archive -allowProvisioningUpdates CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      # Post-process to embed TensorFlowLiteC.framework in .app
            # Post-process to embed TensorFlowLiteC.framework
      - name: Embed TensorFlowLiteC.framework
        run: |
          # Set environment variables
          APP_DIR="federated_slm_app/ios/build/Runner.xcarchive/Products/Applications/Runner.app"
          
          # Path to TensorFlowLiteC.framework in the Pods directory
          FRAMEWORK_DIR="$PWD/federated_slm_app/ios/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.xcframework/ios-arm64/TensorFlowLiteC.framework"
          
          # Check if the framework exists in the directory
          if [ -d "$FRAMEWORK_DIR" ]; then
            # Create a Frameworks directory inside Runner.app if it doesn't exist
            mkdir -p "$APP_DIR/Frameworks"
            
            # Copy the TensorFlowLiteC.framework to the app
            cp -R "$FRAMEWORK_DIR" "$APP_DIR/Frameworks/"
            
            # Optional: Check if the framework was copied successfully
            ls "$APP_DIR/Frameworks/"
          else
            echo "TensorFlowLiteC.framework not found at $FRAMEWORK_DIR"
            exit 1
          fi


      # List contents of the .xcarchive to confirm .app exists
      - name: List contents of .xcarchive
        run: |
          cd federated_slm_app/ios
          ls -R $PWD/build/Runner.xcarchive/Products/Applications/

      # Upload the extracted .app as artifact
      - name: Upload .app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: runner-app
          path: federated_slm_app/ios/build/Runner.xcarchive/Products/Applications/Runner.app
