name: Build iOS App for iOS without signing

on:
  push:
    branches:
      - master  # Set your branch

jobs:
  build:
    runs-on: macos-latest  # Use the macOS runner
    
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'  # Use your Flutter version

      # Cache Flutter dependencies (optional)
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Install dependencies (flutter packages)
      - name: Install dependencies
        run: |
          flutter pub get

      # Clean previous builds (optional but recommended)
      - name: Clean previous builds
        run: |
          flutter clean

      # Build iOS app without signing
      - name: Build iOS app without signing
        run: |
          flutter build ios --no-codesign  # Build without signing

      # Archive and create .ipa (unsigned)
      - name: Archive and create .ipa (unsigned)
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath $PWD/ios/build/Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath $PWD/ios/build/Runner.xcarchive -exportPath $PWD/ios/build/Runner.ipa -exportOptionsPlist /dev/null

      # Upload the .ipa file as an artifact (to download later)
      - name: Upload .ipa as artifact
        uses: actions/upload-artifact@v4
        with:
          name: runner-ipa
          path: ios/build/Runner.ipa
